# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn
    - run: yarn build
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '318.0.0'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - run: gcloud builds submit --tag "gcr.io/$GCP_PROJECT_ID/platform:$GITHUB_SHA"
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --image "gcr.io/$PROJECT_ID/platform:$GITHUB_SHA" \
          --platform "managed" \
          --allow-unauthenticated
