# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy to Cloud Run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: europe-west1
  SERVICE_NAME: platform

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - run: 'yarn ci:format'
      - run: 'yarn ci:lint'
      - run: yarn build
      - uses: cypress-io/github-action@v2
        with:
          command: 'yarn test:cy'
      - name: Setup gcloud
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '318.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Build docker image using Cloud Build
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --quiet \
            --region "$RUN_REGION" \
            --max-instances 1 \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated
